name: Build release

on: workflow_dispatch

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0

      - name: Install
        run: npm ci
      
      - name: Electron rebuild
        run: npm run rebuild
      
      - name: Make
        run: npm run make
      
      - uses: actions/upload-artifact@v3
        with:
          name: flashMe-${{ matrix.os }}
          path: out/make/
